version = 1

[[analyzers]]
name = "shell"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "docker"

  [analyzers.meta]
  dockerfile_paths = ["docker/Dockerfile"]

[[transformers]]
name = "autopep8"

[[transformers]]
name = "ruff"

[[transformers]]
name = "isort"