exp_name: "first_test"
output_dir: "output"
env:
  continuous: False
  target_speeds: [0, 3, 6, 9, 12] # For discrete speed control
  desired_speed: 12 # For continuous speed control
  dt: 0.05
  # Change this to match your server user
  port: 2000
  render: false
  ego_vehicle_filter: "vehicle.lincoln*"
  num_veh: 3
  num_ped: 2
  max_steps: 500
  CAM_RES: 1024
  max_waypt: 200
  pedestrian_proximity_threshold: 5.0
  reward_weights:
    # Route completion reward
    c_completion: 100.0
    # Collision penalty with vehicle
    c_terminal_collision: -100.0
    # Collision penalty with pedestrian
    c_terminal_pedestrian_collision: -200.0
    # Timeout penalty
    c_terminal_timeout: -10.0
    # Velocity reward constants
    c_v_eff_under_limit: 1.0
    c_v_eff_over_limit: -2.0
    # Penalty for needing another step
    r_step: -0.0
    # Penalty for non-smooth actions
    c_action_reg: -0.0
    # Penalty for yaw delta w.r.t. road heading
    c_yaw_delta: -0.0
    # Penalty for lateral deviation
    c_lat_dev: -0.0
    # Distance from goal penalty
    c_dist_from_goal: 3.5
    # Progress reward
    c_progress: 0.0
    # Penalty for being close to pedestrians
    c_pedestrian_proximity: -10.0