channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2023.01.10
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=1.1.1t
  - pip=23.0.1
  - python=3.8.16
  - readline=8.2
  - setuptools=67.8.0
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - cloudpickle==2.2.1
      - cmake==3.27.0
      - contourpy==1.1.0
      - cycler==0.11.0
      - farama-notifications==0.0.4
      - filelock==3.12.2
      - fonttools==4.41.1
      - gymnasium==0.28.1
      - importlib-metadata==6.6.0
      - importlib-resources==6.0.0
      - jax-jumpy==1.0.0
      - jinja2==3.1.2
      - kiwisolver==1.4.4
      - lit==16.0.6
      - markupsafe==2.1.3
      - matplotlib==3.7.2
      - mpmath==1.3.0
      - networkx==3.1
      - numpy==1.24.3
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - packaging==23.1
      - pandas==2.0.3
      - pillow==10.0.0
      - pygame==2.4.0
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pytz==2023.3
      - pyyaml==6.0.1
      - six==1.16.0
      - stable-baselines3==2.0.0
      - sympy==1.12
      - torch==2.0.1
      - triton==2.0.0
      - typing-extensions==4.6.3
      - tzdata==2023.3
      - zipp==3.15.0
