name: Push to Docker Hub

on:
  push:
    paths:
      - "docker/**"
      - ".github/workflows/docker-publish.yml"

jobs:
  build-and-publish:
    strategy:
      matrix:
        cuda: ["11.8.0", "11.4.3"]
        carla: ["0.9.10.1"]
    runs-on: ubuntu-latest
    steps:
      - name: Reclaim disk space as specified at https://github.com/actions/runner-images/issues/2840
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: faizansana
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Build and push container
        uses: docker/build-push-action@v4
        with:
          context: ./docker
          file: ./docker/Dockerfile
          build-args: |
            CUDA_VERSION=${{ matrix.cuda }}
            CARLA_VERSION=${{ matrix.carla }}
          push: true
          tags: faizansana/intersection-carla-gym:cuda-${{ matrix.cuda }}-carla-${{ matrix.carla }}