name: Push to Docker Hub

on:
  push:
    branches:
      - "main"
    paths:
      - "docker/**"
      - ".github/workflows/docker-publish.yml"
  pull_request:
    paths:
      - "docker/**"
      - ".github/workflows/docker-publish.yml"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-and-publish:
    strategy:
      fail-fast: false
      matrix:
        cuda: ["12.0.0"]
        carla: ["0.9.10.1"]
    runs-on: ubuntu-latest
    steps:
      - name: Reclaim disk space as specified at https://github.com/actions/runner-images/issues/2840
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push container
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          file: ./docker/Dockerfile
          build-args: |
            CUDA_VERSION=${{ matrix.cuda }}
            CARLA_VERSION=${{ matrix.carla }}
          push: true
          tags: ghcr.io/${{ github.repository }}:cuda-${{ matrix.cuda }}-carla-${{ matrix.carla }}